create new tuning exercise separate from nested resa
slds-lmu/lecture_i2ml pull request #1048
Opened 2023-01-10 11:58 UTC by lisa-wm

2023-01-12 08:48 UTC, ludwigbothmann commented
![](https://github.trello.services/images/mini-trello-icon.png) [create new tuning exercise material](https://trello.com/c/8xbFGson/256-create-new-tuning-exercise-material)

2023-01-20 17:02 UTC, ludwigbothmann requested changes
Just 2 mini changes. But there are conflicts that prevent from merging right now. Please resolve those and upload the sheet to moodle (independently from resolving the conflicts..) thx @lisa-wm !

2023-01-20 17:02 UTC, ludwigbothmann commented on exercises/tuning/ex_rnw/ex_tuning_knn.Rnw
> +  more more influential for smaller neighborhoods.
remove one "more"

2023-01-20 17:02 UTC, ludwigbothmann commented on exercises/tuning/ex_rnw/sol_tuning_knn.Rnw
> +    \footnotesize{\url{https://en.wikipedia.org/wiki/Kernel_%28statistics%29#/media/File:Kernels.svg}}
Footnotesize does not end after the caption here..

2023-01-23 19:26 UTC, lisa-wm commented
> Just 2 mini changes. But there are conflicts that prevent from merging right now. Please resolve those and upload the sheet to moodle (independently from resolving the conflicts..) thx @lisa-wm !

conflicts solved 🙏🏻

2023-01-26 16:35 UTC, ludwigbothmann approved these changes

2023-01-26 16:35 UTC, merged