Python classification
slds-lmu/lecture_i2ml pull request #1057
Opened 2023-02-06 18:32 UTC by StefanieSwz

Exercise Sheet (.Rnw), Solution Sheet (Jupiter .ipynb, .tex, .pdf) for Python: Only for Classification 2, as Classification 1 has no programming included

2023-03-09 19:48 UTC, StefanieSwz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Python Exercise I2ML: Sheet 4 Classification 2](https://trello.com/c/AjvT6OAS/265-python-exercise-i2ml-sheet-4-classification-2)

2023-03-10 16:10 UTC, ludwigbothmann reviewed
See Mattermost, thx @StefanieSwz :pray:

2023-03-28 16:18 UTC, ludwigbothmann requested changes
2 kleine Kommentare. Außerdem hier bitte auch das naming noch anpassen wie in supervised-regression. danke @StefanieSwz !

2023-03-28 16:18 UTC, ludwigbothmann commented on exercises-pdf/sol_classification_2.pdf
In der Lsg. von der 1a sind 2 warnings. Bekommst Du die noch weg?

2023-03-28 16:18 UTC, ludwigbothmann commented on exercises/supervised-classification/sol_classification_2_py.ipynb
Sieht sehr gut aus. Am Ende könnten in der Confusion Matrix noch die Werte anders formatiert sein: Da steht gerade `3.7e+02`, da fände ich eine `370` irgendwie schöner :)

2023-04-19 14:58 UTC, ludwigbothmann approved these changes
thx @StefanieSwz ! :pray:

2023-04-19 14:58 UTC, merged