Python sup regression
slds-lmu/lecture_i2ml pull request #1062
Opened 2023-02-13 12:45 UTC by StefanieSwz

New Branch for the Supervised regression exercise sheet in Python
- Exercise .Rnw and .pdf for Python
- Exercise .Rnw and .pdf for R and Python (unspecific phrasing)
- Solution .ipynb Jupiter Notebook
- I2ML_env.yml in supervised-regression folder to prevent merge conflicts (cleaned requirement list)

2023-03-09 19:48 UTC, StefanieSwz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Python Exercise 2: Regression I2ML](https://trello.com/c/XLVtrQE3/263-python-exercise-2-regression-i2ml)

2023-03-24 17:07 UTC, ludwigbothmann reviewed
weiter bin ich heute leider nicht gekommen..

2023-03-25 10:36 UTC, StefanieSwz commented on exercises-pdf/ex_regression_R_py.pdf
See also DM Mattermost: ex_regression.pdf is the currently used Exercise sheet, ex_regression_R_py.pdf the new version for both R and Python. --> rename ex_regression_R_py.pdf to ex_regression.pdf , then either delete current ex_regression.pdf or rename it to ex_regression_old.pdf ?

2023-03-25 11:05 UTC, StefanieSwz commented on exercises/supervised-regression/ex_rnw/ex_lrn_R_py.Rnw
> +    (Hint: use \texttt{mlr3::mlr\_learners\$keys()} to see all available
Done

2023-03-28 15:58 UTC, ludwigbothmann requested changes
Super sieht das jetzt aus :+1: Habe paar Kleinigkeiten gefixed. Wenn Du jetzt noch das naming wie besprochen anpasst, können wir es mergen :) danke @StefanieSwz

2023-03-28 15:58 UTC, ludwigbothmann commented on exercises-pdf/ex_regression_R_py.pdf
Passt :+1: (Also bis auf das naming, wir überschreiben einfach `ex_regression.pdf`)

2023-03-28 15:58 UTC, ludwigbothmann commented on exercises-pdf/sol_regression.pdf
Passt auch :+1:

2023-04-24 13:49 UTC, merged