Python nested resampling
slds-lmu/lecture_i2ml pull request #1121
Opened 2023-07-22 11:46 UTC by StefanieSwz

See Meta-Comments in Trello Card

Modified: 
- exercises-pdf/ex_nested_resampling.pdf
- exercises/nested-resampling/ex_nested_resampling.Rnw
- exercises/nested-resampling/ex_rnw/ex_automl.Rnw
- exercises/nested-resampling/ex_rnw/ex_kaggle.Rnw

Added:
- exercises/nested-resampling/sol_nested_resampling_py.ipynb
- exercises/nested-resampling/I2ML_env.yml

2023-07-22 11:50 UTC, StefanieSwz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Python Exercise I2ML: Sheet 11 Nested Resampling](https://trello.com/c/ki3wKxnX/294-python-exercise-i2ml-sheet-11-nested-resampling)

2023-09-14 15:23 UTC, ludwigbothmann requested changes
Liebe @StefanieSwz sieht schon sehr gut aus, danke! Das war ja einiges an Arbeit, ist ja komplett anders in Python als in R.. Paar Kommentare habe ich.

2023-09-14 15:23 UTC, ludwigbothmann commented on exercises/nested-resampling/ex_rnw/ex_automl.Rnw
>  \end{enumerate}
Eigentlich fehlt hier noch, dass man den Graph Learner dann auch final tuned + trainiert, so dass man ihn zur Prognose nutzen kann, oder? Hier habe ich ja "nur" einen geschätzten GE?

2023-09-14 15:23 UTC, ludwigbothmann commented on exercises/nested-resampling/ex_rnw/ex_automl.Rnw
> +  encode the target \texttt{"diabetes"} and perform a stratified \texttt{train\_test\_split}.
encoden als was? Schreib vlt. dazu, dass es 0-1 sein soll.

2023-09-14 15:23 UTC, ludwigbothmann commented on exercises/nested-resampling/sol_nested_resampling_py.ipynb
> +    "# combine both classifier with a soft voting ensembling\n",
"classifiers"

2023-09-14 15:23 UTC, ludwigbothmann commented on exercises/nested-resampling/ex_rnw/ex_automl.Rnw
> +  \item A very common ensembling technique is to predict according to the decisions of numerous estimators. This is refered to as \texttt{VotingClassifier} and enables you to predict the class label
Hier fehlt jetzt die Aufgabe :) Also "VotingClassifier erstellen"..

2023-09-14 15:23 UTC, ludwigbothmann commented on exercises/nested-resampling/ex_rnw/ex_automl.Rnw
> +  \item Now you have a learner object just like any other.
Heißt es in sklearn nicht "estimator" statt "learner"?

2023-09-14 15:23 UTC, ludwigbothmann commented on exercises/nested-resampling/ex_rnw/ex_automl.Rnw
> +  Take a look at its tunable hyperparameters.
Das fehlt in der Lösung.

2023-09-14 15:23 UTC, ludwigbothmann commented on exercises/nested-resampling/sol_nested_resampling_py.ipynb
> +    "# print performanced aggregated over all folds\n",
"performance"

2023-09-14 15:23 UTC, ludwigbothmann commented on exercises/nested-resampling/ex_rnw/ex_automl.Rnw
> +\end{enumerate}
Analog zur R-Aufgabe: Eigentlich fehlt hier jetzt noch, dass man den VotingClassifier final tuned und trainiert, so dass man auf neuen Daten vorhersagen kann. Könntest du das bitte noch einbauen?

2023-09-14 15:23 UTC, ludwigbothmann commented on exercises/nested-resampling/ex_rnw/ex_automl.Rnw
> +\end{enumerate}
Jetzt fällt mir auch auf, dass die Testdaten ja komplett ignoriert werden - wieso eigentlich? Das NR kann ich doch auf allen Daten machen? Man *könnte* jetzt natürlich auf den Trainigsdaten noch tunen (mit GridSearchCV), dann trainieren (macht GridSearchCV mit etwas Glück sogar direkt selbst mit den besten Hyps) und dann beispielhaft auf den Testdaten vorhersagen, dann hätte sich der Train-Test-Split gelohnt. Was meinst du? :)

2023-09-14 15:23 UTC, ludwigbothmann commented on exercises/nested-resampling/sol_nested_resampling_py.ipynb
- Läuft schon mal durch :+1:

2023-10-26 14:37 UTC, closed without merging