Solution Notebook, and updated Exercise Sheet
slds-lmu/lecture_i2ml pull request #1136
Opened 2023-10-03 10:19 UTC by StefanieSwz

See Meta-Comments in Trello Card

Modified:

exercises-pdf/ex_nested_resampling.pdf
exercises/nested-resampling/ex_nested_resampling.Rnw
exercises/nested-resampling/ex_rnw/ex_automl.Rnw
exercises/nested-resampling/ex_rnw/ex_kaggle.Rnw

Added:

exercises/nested-resampling/sol_nested_resampling_py.ipynb

Note: already up-to-date with global environment in /exercise folder

2023-10-03 11:49 UTC, StefanieSwz commented
![](https://github.trello.services/images/mini-trello-icon.png) [Python Exercise I2ML: Sheet 11 Nested Resampling](https://trello.com/c/ki3wKxnX/294-python-exercise-i2ml-sheet-11-nested-resampling)

2023-10-06 12:54 UTC, ludwigbothmann requested changes

2023-10-06 12:54 UTC, ludwigbothmann commented on exercises/nested-resampling/ex_rnw/ex_automl.Rnw
> +  and overall (as mean). According to your results, determin the best classifier object.
"determine"

2023-10-06 12:54 UTC, ludwigbothmann commented on exercises/nested-resampling/ex_rnw/ex_automl.Rnw
> +  \item Lastly, evaluate the performance on the test set. Think about the imbalance of your data set and how this is affecting the performance measurement accuracy. Try to find a better metric and co
Vielleicht stehe ich auf dem Schlauch, aber: Hast du meinen Kommentar aus dem anderen PR eingebaut, also ist das hier dann das Modell, dass auf den ganzen Trainingsdaten noch mal getuned und trainiert wurde?

2023-10-06 12:54 UTC, ludwigbothmann commented on exercises/nested-resampling/ex_rnw/ex_automl.Rnw
>    \texttt{extract\_inner\_tuning\_archives()}.
Hier hast du glaube ich einen Kommentar im anderen PR übersehen, kann das sein?

2023-10-26 07:00 UTC, ludwigbothmann commented on exercises/nested-resampling/ex_rnw/ex_automl.Rnw
>    \texttt{extract\_inner\_tuning\_archives()}.
Solved, lassen wir so weil mlr3 hier nicht macht, was wir wollen.

2023-10-26 07:01 UTC, ludwigbothmann reviewed
Ein Kommentar ist noch offen

2023-10-26 14:40 UTC, merged