quick fixes for nutshell slides
slds-lmu/lecture_i2ml pull request #1148
Opened 2023-10-26 13:56 UTC by manuelhelmerichs

2023-10-31 10:01 UTC, ludwigbothmann requested changes

2023-10-31 10:01 UTC, ludwigbothmann commented on slides/all/slides-i2ml-nutshell.tex
> +\input{../cart/slides-cart-nutshell.tex}
Nicht, dass das mit den chapter-order-files bei nur einer datei jeweils Sinn machen würde, aber es sollte doch einheitlich sein. Kannst du das einfach alles so machen wie hier, also ohne das chapter-order?

2023-11-01 10:22 UTC, manuelhelmerichs commented
![](https://github.trello.services/images/mini-trello-icon.png) [Nutshell quick fixes](https://trello.com/c/AvsvrzMA/322-nutshell-quick-fixes)

2023-11-01 14:03 UTC, ludwigbothmann approved these changes

2023-11-01 14:03 UTC, merged