revise classif 1 sheet
slds-lmu/lecture_i2ml pull request #1153
Opened 2023-11-06 10:34 UTC by lisa-wm

2023-11-06 14:10 UTC, lisa-wm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Revise exercise classif I](https://trello.com/c/4kBa9jDj/324-revise-exercise-classif-i)

2023-11-08 13:25 UTC, ludwigbothmann requested changes
Hi @lisa-wm das sieht soweit alles ganz gut aus. Einziger, aber möglicherweise größerer Punkt: Jetzt haben wir (nagut, ich..) den Chunk zu linear classifiers für Gruppe B rausgenommen, und dabei nicht bedacht, dass das Auswirkungen auf die Übung haben könnte. Die 2 kann man denke ich trotzdem machen. Aber evtl. ist das jetzt doch doof für die 3? => Besser mündlich.

2023-11-08 13:25 UTC, ludwigbothmann commented on exercises/supervised-classification/ex_rnw/ex_hyperplanes.Rnw
Wie schlimm ist das jetzt, dass wir genau den Chunk zu den linear classifieres rausgenommen haben für B? :) https://docs.google.com/spreadsheets/d/1Eu2ElIamHmObB6WwjGqipuFuR8YEfIwdyfdLO2Hsm9U/edit#gid=0

2023-11-08 13:25 UTC, ludwigbothmann commented on exercises/supervised-classification/ex_rnw/sol_hyperplanes.Rnw
> +\item $\theta_0 = 0, \theta_1 = \theta_2 = 1$ $\rightsquigarrow$ e.g., (0, 0) and (1, -1).
- du meinst hier, dass (x1, x2) = (0,0) bzw. (x1,x2) = (1,-1) oder? Dann schreib das besser noch dazu
- im Plot steht dann x und y, das kommt aber in der Angabe gar nicht vor => besser angleichen?

2023-11-08 13:25 UTC, ludwigbothmann commented on exercises/supervised-classification/ex_classification_1.Rnw
>  \aufgabe{Decision Boundaries \& Thresholds in Logistic Regression}{
Müssen wir dann die (a) hier rausnehmen für Gruppe B? Weil der entsprechende VL-chunk rausgenommen wurde?

2023-11-10 09:52 UTC, ludwigbothmann approved these changes

2023-11-10 09:52 UTC, merged