set up exercise regression anew
slds-lmu/lecture_i2ml pull request #656
Opened 2021-09-16 09:45 UTC by lisa-wm

2021-10-04 10:26 UTC, lisa-wm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercise 2 - Regression](https://trello.com/c/5xH92s1e/29-exercise-2-regression)

2021-10-14 09:32 UTC, ludwig-max reviewed
Das sieht sehr gut aus, @lisa-wm alle Lernziele sind abgedeckt. Habe nur kleinere Anmerkungen, starte gern mit der Lösung.

2021-10-14 09:32 UTC, ludwig-max commented on exercises/supervised-regression/ex_rnw/ex_lrn.Rnw
> +  \item How are the key concepts you learned about in the lecture videos
"Key concepts" genauer spezifizieren, also einfach alle aufzählen, nach denen gefragt ist.

2021-10-14 09:32 UTC, ludwig-max commented on exercises/supervised-regression/ex_rnw/ex_regr_losses.Rnw
> +In this exercise, we will examine loss functions for regression problems
"regression task" - habe ich aber schon geändert.

2021-10-14 09:32 UTC, ludwig-max commented on exercises/supervised-regression/ex_rnw/ex_regr_losses.Rnw
> +  \item Consider the above linear regression problem. How will the model
"Describe how the model parameters.." => Wann immer möglich, sind Aufforderungen besser als Fragen.

2021-10-14 09:32 UTC, ludwig-max commented on exercises/supervised-regression/ex_rnw/ex_regr_losses.Rnw
> +  \item[c)] \textcolor{orange}{Zu schwer?}
Hm, ja ich weiß auch nicht. Da wir in der VL bisher auch nicht so mathematisch unterwegs sind, würde ich das hier glaube ich eher weglassen.

2021-10-14 09:32 UTC, ludwig-max commented on exercises/supervised-regression/ex_rnw/ex_polynomial.Rnw
> +  \item State the empirical risk w.r.t. $\thetab$ for a member of our hypothesis
Das verstehe ich nicht ganz, also das "for a member": Dafür muss ich dann konkrete Werte für theta einsetzen? Wenn ja, verstehe ich das "wrt theta" nicht.

2021-10-14 09:32 UTC, ludwig-max commented on exercises/supervised-regression/ex_rnw/ex_polynomial.Rnw
> +  Should you opt for a more flexible model class (i.e., a hypothesis space
"Describe the advantages and disadvantages that a more flexible model class would have. Would you opt for a more flexible model class?"

2021-10-14 09:32 UTC, ludwig-max commented on exercises/supervised-regression/ex_rnw/ex_lm_abalone.Rnw
> +See \url{http://archive.ics.uci.edu/ml/datasets/Abalone} for more details.
Die haben eine neue Seite in beta (aber dafür https), vlt. nehmen wir besser die? https://archive-beta.ics.uci.edu/ml/datasets/abalone

2021-10-14 09:32 UTC, ludwig-max commented on exercises/supervised-regression/ex_rnw/ex_lm_abalone.Rnw
> +  "http://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data"
ggf hier auch die neue URL

2021-10-14 09:32 UTC, ludwig-max commented on exercises/supervised-regression/ex_rnw/ex_lm_abalone.Rnw
> +  \texttt{task} like so \textcolor{orange}{(necessary if they have heard the
nein, wird dann nicht nötig sein. Aber

- schieb die Zeile mit "data <-" nach oben in den chunk
- neue Aufgabe b in dem man nur den task definieren soll
- und dann in der neuen c (alte b) nur den learner definieren und trainieren (und: "to train" statt "to fit")

2021-11-05 15:31 UTC, ludwig-max requested changes
Sieht mega gut aus @lisa-wm :) nur die Gerade com L1 loss noch, dann passt's (mini typos habe ich selbst gefixt)

2021-11-05 15:31 UTC, ludwig-max commented on exercises/supervised-regression/ex_rnw/sol_regr_losses.Rnw
> +<<echo=FALSE, message=FALSE, fig.align="left", fig.height=3, fig.width=6>>=
Die Gerade vom L1 loss ist hier nicht drin, oder?

2021-11-05 15:58 UTC, ludwig-max commented on exercises/supervised-regression/ex_rnw/sol_regr_losses.Rnw
> +<<echo=FALSE, message=FALSE, fig.align="left", fig.height=3, fig.width=6>>=
passt

2021-11-05 16:00 UTC, ludwig-max approved these changes

2021-11-05 16:00 UTC, merged