new eval I exercise
slds-lmu/lecture_i2ml pull request #700
Opened 2021-11-21 12:42 UTC by lisa-wm

2021-11-21 12:43 UTC, lisa-wm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercise 5 & 6 - Evaluation](https://trello.com/c/aytXGQIZ/36-exercise-5-6-evaluation)

2021-11-23 16:15 UTC, ludwig-max requested changes
Liebe @lisa-wm wie üblich gefällt mir das alles schon sehr gut! Ein paar Kommentare inline.

2021-11-23 16:15 UTC, ludwig-max commented on exercises/evaluation/ex_rnw/sol_train_test_split.Rnw
> +  ordered by feature value, which is obviously not a good idea and leads to a
"..which is not a good idea because this is not a random sample and covers only a very small area of the feature space, and leads.."

2021-11-23 16:15 UTC, ludwig-max commented on exercises/evaluation/ex_rnw/sol_train_test_split.Rnw
> +  we leave little data to test on.
ist das der richtige Grund, dass es wenige Testdaten sind?

2021-11-23 16:15 UTC, ludwig-max commented on exercises/evaluation/ex_rnw/ex_train_test_split.Rnw
> +  \var_{\mathcal{S}}(\hat y) + \E_{\Pxy}(y ~|~ \xv)$$
am Ende + Var?

2021-11-23 16:15 UTC, ludwig-max commented on exercises/evaluation/ex_rnw/ex_train_test_split.Rnw
> +  This sampling process we denote by $\mathcal{S}$.
Das mit dem S würde ich hier glaube ich so nicht verstehen..

2021-11-23 16:15 UTC, ludwig-max commented on exercises/evaluation/ex_rnw/sol_train_test_split.Rnw
> +    + \var_{\Pxy}(y ~|~ \xv) \\
Wieso ist da jetzt vorne noch ein E drum rum?

2021-11-23 16:18 UTC, lisa-wm commented on exercises/evaluation/ex_rnw/ex_regr_metrics.Rnw
> +y_test <- 10 + 3 * sin(0.15 * pi * x_test) + rnorm(length(x_test), sd = 0.1)
Das war ziemlich finicky, ich hab ewig rumprobiert, bis die zwei Metriken tatsächlich in gegenläufige Richtungen zeigen... wenn es nicht schlimm ist, würde ich es also gerne so lassen

2021-11-24 04:50 UTC, lisa-wm commented on exercises/evaluation/ex_rnw/ex_train_test_split.Rnw
> +  This sampling process we denote by $\mathcal{S}$.
im Sinne von "kapieren" oder du hast eine andere Interpretation?

2021-11-24 04:55 UTC, lisa-wm commented on exercises/evaluation/ex_rnw/sol_regr_metrics.Rnw
> +y_train <- 10 + 3 * sin(0.15 * pi * x_train) + rnorm(length(x_train), sd = 0.5)
Ja, super niedrige Frequenz (siehe auch Def train/test data). Meinst du mit "wahr" ohne noise?

2021-11-24 04:58 UTC, lisa-wm commented on exercises/evaluation/ex_rnw/sol_train_test_split.Rnw
> +    + \var_{\Pxy}(y ~|~ \xv) \\
Weil die Differenz zwischen ist-Schätzung und optimaler Schätzung durch den sampling process stochastisch ist

2021-11-24 04:58 UTC, lisa-wm commented on exercises/evaluation/ex_rnw/sol_train_test_split.Rnw
> +  we leave little data to test on.
Das war mein Verständnis für Varianz im GE, klär mich gerne auf :)

2021-11-25 11:42 UTC, ludwig-max commented on exercises/evaluation/ex_rnw/sol_train_test_split.Rnw
> +  we leave little data to test on.
ja, stimmt, weiß auch nicht was ich da wollte :)

2021-11-25 11:43 UTC, ludwig-max commented on exercises/evaluation/ex_rnw/ex_regr_metrics.Rnw
> +y_test <- 10 + 3 * sin(0.15 * pi * x_test) + rnorm(length(x_test), sd = 0.1)
aber wieso sollen die in zwei unterschiedliche Richtungen zeigen? So kommen die Daten ja aus unterschiedlichen DGP, das wollen wir ja nicht, oder?

2021-11-25 11:44 UTC, ludwig-max commented on exercises/evaluation/ex_rnw/ex_train_test_split.Rnw
> +  This sampling process we denote by $\mathcal{S}$.
im Sinne von "kapieren". Was macht das S da genau? Also dass man y-dach als ZV sieht, verstehe ich; aber was S genau ist iwie nicht. Vlt. stehe ich aber auch nur auf dem Schlauch

2021-11-25 11:45 UTC, ludwig-max commented on exercises/evaluation/ex_rnw/sol_train_test_split.Rnw
> +    + \var_{\Pxy}(y ~|~ \xv) \\
was heißt ist-schätzung und optimale schätzung?

2021-11-25 12:02 UTC, lisa-wm commented on exercises/evaluation/ex_rnw/ex_regr_metrics.Rnw
> +y_test <- 10 + 3 * sin(0.15 * pi * x_test) + rnorm(length(x_test), sd = 0.1)
na ich will ja darauf raus, dass MAE und MSE unterschiedliche Entscheidungen liefern. Und der true DGP ist ja derselbe, nur das noise level bei den Trainingsdaten ist höher. kann nochmal probieren, ob ich mit gleichem noise die Situation hinbiegen kann

2021-11-25 14:48 UTC, ludwig-max commented on exercises/evaluation/ex_rnw/ex_regr_metrics.Rnw
> +y_test <- 10 + 3 * sin(0.15 * pi * x_test) + rnorm(length(x_test), sd = 0.1)
- aber dann ist ja nicht der wahre DGP gleich, sondern nur der EW davon, oder? und
- Wäre es nicht eine schönere Botschaft, dass ein Polynom vom Grad 21 eigentlich immer eine schlechte Idee ist?

2021-11-25 14:49 UTC, ludwig-max commented on exercises/evaluation/ex_rnw/ex_train_test_split.Rnw
> +  This sampling process we denote by $\mathcal{S}$.
ist denke ich gelöst mit den neuen änderungen :)

2021-11-25 14:49 UTC, ludwig-max commented on exercises/evaluation/ex_rnw/sol_train_test_split.Rnw
> +    + \var_{\Pxy}(y ~|~ \xv) \\
ist denke ich dann auch gelöst

2021-11-26 13:11 UTC, ludwig-max approved these changes

2021-11-26 13:11 UTC, merged