drafted second eval exercise
slds-lmu/lecture_i2ml pull request #704
Opened 2021-11-29 09:14 UTC by lisa-wm

2021-11-29 09:16 UTC, lisa-wm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Exercise 5 & 6 - Evaluation](https://trello.com/c/aytXGQIZ/36-exercise-5-6-evaluation)

2021-11-29 12:54 UTC, ludwig-max requested changes
Liebe @lisa-wm vielen Dank für den Draft! Diesmal habe ich ein paar mehr Anmerkungen, siehe inline.

2021-11-29 12:54 UTC, ludwig-max commented on exercises/evaluation/ex_rnw/ex_of_uf.Rnw
> +    \item Large training set \& linear regression learner
Kommt auf die Daten an, oder? Wenn der DGP in H ist, ist das ja perfekt und weder over- noch underfitting?

2021-11-29 12:54 UTC, ludwig-max commented on exercises/evaluation/ex_rnw/ex_of_uf.Rnw
> +    \item Noisy training data \& high-degree polynomial regression learner
:+1:

2021-11-29 12:54 UTC, ludwig-max commented on exercises/evaluation/ex_rnw/ex_of_uf.Rnw
> +    \item Few observations of many features \& linear regression learner
Ist das nicht mehr ein Identifizierbarkeits- als ein Overfittingproblem?

2021-11-29 12:54 UTC, ludwig-max commented on exercises/evaluation/ex_rnw/ex_of_uf.Rnw
> +    \item Data with class overlap \& LDA learner
QDA würde aber ja genauso wenig perfekt sein, oder? Außerdem hat man ja egtl. immer class overlap in der Realität?

2021-11-29 12:54 UTC, ludwig-max commented on exercises/evaluation/ex_rnw/ex_of_uf.Rnw
> +  under- or overfitting behavior.
wenn man die Aufgabe so lässt: "and explain why"

2021-11-29 12:54 UTC, ludwig-max commented on exercises/evaluation/ex_rnw/sol_of_uf.Rnw
> +  Recall how we defined the two variants of ill fit:
Für eine Definition von ill fit müsste man UF und OF aber noch mit einem Referenzwert vergleichen, oder? So ist es ja eher ein allgemeines Maß.

2021-11-29 12:54 UTC, ludwig-max commented on exercises/evaluation/ex_rnw/ex_of_uf.Rnw
> +  \item For the following situations, state whether you would rather expect
Die Situationen sind mir iwie zu ungenau. Hatten wir das auf der Klausur oder Nachklausur nicht ähnlich und (imo) klarer?

2021-11-29 12:54 UTC, ludwig-max commented on exercises/evaluation/ex_rnw/sol_resa_mlr3.Rnw
> +  However, we see a glaring optimistic bias when we use a single 90\%-10\%
Das ist nicht wirklich ein optimistischer Bias sondern einfach Glück/Pech, oder? Also eher ein Artefakt der höheren Variabilität?

2021-11-29 12:54 UTC, ludwig-max commented on exercises/evaluation/ex_rnw/sol_resa_mlr3.Rnw
> +  sufficient number of folds yields pretty stable estimates.
Woran genau sehe ich, dass das pretty stable ist?

2021-12-03 13:45 UTC, ludwig-max approved these changes
top, danke @lisa-wm

2021-12-03 13:46 UTC, merged