added new notation
slds-lmu/lecture_i2ml pull request #720
Opened 2021-12-11 05:53 UTC by lisa-wm

added new eval notation proposed for latex-math

2021-12-11 05:54 UTC, lisa-wm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add new eval notation to latex-math & check eval/tuning cheatsheet](https://trello.com/c/tmTOYq8C/108-add-new-eval-notation-to-latex-math-check-eval-tuning-cheatsheet)

2021-12-16 11:42 UTC, ludwig-max requested changes
3 times "ind" instead of "in"

2021-12-16 11:42 UTC, ludwig-max commented on slides/evaluation/slides-evaluation-generr.tex
> +  % $$\E_{\D\sim(\Pxy)^{\ntrain}}\left[\frac{1}{n}\sumin L\left(\yi, \fhDlam(\xi)\right)  \right] \xrightarrow{n \to \infty} \GE(\in, \lamv, \ntrain, \rhoL) .$$
should be "\ind"? (Yes, is commented out, but if it's not deleted, it should be correct still)

2021-12-16 11:42 UTC, ludwig-max commented on slides/evaluation/slides-evaluation-generr.tex
> +  % $$\GEh_{\Dtrain, \Dtest}(\in,
ind

2021-12-16 11:42 UTC, ludwig-max commented on slides/evaluation/slides-evaluation-generr.tex
> +  % \in(\D_{\mathrm{train}}, \lamv)} \right).$$
ind

2021-12-20 15:03 UTC, merged