drafted test exam
slds-lmu/lecture_i2ml pull request #724
Opened 2021-12-15 14:29 UTC by lisa-wm

2021-12-15 14:32 UTC, lisa-wm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Test Exam](https://trello.com/c/ncq0Viu0/62-test-exam)

2021-12-16 16:42 UTC, ludwig-max requested changes
Gefällt mir schon ganz gut Ihr beiden :) Die 1 ist etwas komisch, vlt sprechen wir da noch mal?

2021-12-16 16:42 UTC, ludwig-max commented on exercises/testexam/ex_rnw/ex_poly.Rnw
> +State the hypothesis space for a univariate polynomial regression model with
Die Aufgabe verstehe ich nicht ganz, was machen diese Faktoren? Gehen doch im Endeffekt eh in den thetas auf? Formulierung müssten wir dann auch noch überarbeiten.

2021-12-16 16:42 UTC, ludwig-max commented on exercises/testexam/ex_rnw/sol_knn_gower.Rnw
> +Therefore, the $1$-neighborhood $N_1(\xv^{*})$ of the red point $\xv^{*}$ is the point $\xv^{(3)}$, which is the observation with the lowest gower distance.
vlt oben einmal definieren, welcher punkt welcher ist

2021-12-22 12:20 UTC, ludwig-max approved these changes
great, thx @holgstr and @lisa-wm

2021-12-22 12:20 UTC, merged