added regularized risk to cheatsheet
slds-lmu/lecture_i2ml pull request #734
Opened 2022-01-10 07:54 UTC by lisa-wm

2022-01-10 07:56 UTC, lisa-wm commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add regularized risk to cheatsheet](https://trello.com/c/Em1CQaWs/130-add-regularized-risk-to-cheatsheet)

2022-01-13 10:48 UTC, ludwig-max requested changes

2022-01-13 10:48 UTC, ludwig-max commented on cheatsheets/cheatsheet_notation/cheatsheet_notation.tex
> +\textbf{Regularized risk}: $\riskr: \Hspace
Könntest Du die Reihenfolge von Name - Räumen - Funktionsdef. vereinheitlichen mit riskf und riskef? Mir persönlich gefällt Name am Anfang (so wie Du es hier gemacht hast) besser. Danke!

2022-01-14 12:51 UTC, ludwig-max approved these changes
Top @lisa-wm Danke!

2022-01-14 12:51 UTC, merged