added hat symbols to theta
slds-lmu/lecture_i2ml pull request #738
Opened 2022-01-17 13:58 UTC by lisa-wm

2022-01-17 15:29 UTC, ludwig-max requested changes
Vor Teil (a) müsste es noch mal ein thetah geben (in pi(..))

2022-01-18 05:37 UTC, lisa-wm commented
Da bin ich mir nicht sicher, imho passt es beim ersten pi, weil wir da die zu schätzende, wahre Wahrscheinlichkeit meinen, beim zweiten ist das hat symbol ja schon über pi (also gedacht eigentlich über dem ganzen Ausdruck), und pi_hat (x | theta) = theta_hat^T x?

2022-01-18 14:30 UTC, ludwig-max commented
Beim ersten passt es auf jeden Fall, da stimme ich Dir zu. Aber beim 2.: Was spricht gegen pi_hat (x | theta_hat)?

2022-01-19 13:49 UTC, lisa-wm commented
Hast Recht, habs geändert :)

2022-01-19 14:12 UTC, ludwig-max approved these changes

2022-01-19 14:12 UTC, merged

2022-01-19 14:12 UTC, ludwig-max commented
danke :)