IC 11 tuning nested res
slds-lmu/lecture_i2ml pull request #743
Opened 2022-01-25 17:10 UTC by holgstr

2022-01-25 17:11 UTC, holgstr commented
![](https://github.trello.services/images/mini-trello-icon.png) [IC week #11](https://trello.com/c/3ougOGtQ/136-ic-week-11)

2022-01-27 18:01 UTC, ludwig-max requested changes
Danke @holgstr Das passt für morgen. Aber könntest Du in der Lösung noch mit angeben, dass bei 3 man nested resampling machen könnte und dann wüsste, dass es wenigstens nur noch pessimistically biased ist? Danke.

2022-01-27 22:01 UTC, holgstr commented
@ludwig-max Absolut, ich habe es noch hinzugefügt :)

2022-01-31 08:50 UTC, ludwig-max approved these changes

2022-01-31 08:50 UTC, merged