visualization of qda decision boundaries with diff. ranges
slds-lmu/lecture_i2ml pull request #792
Opened 2022-05-29 07:40 UTC by laefrost

2022-05-30 07:49 UTC, ludwigbothmann requested changes

2022-05-30 07:49 UTC, ludwigbothmann commented on slides/supervised-classification/rsrc/fig-reg_class_qda.R
> +  means <- learner_qda$model$means
das muss `learner` sein, ohne `_qda`, oder?

2022-05-30 11:05 UTC, ludwigbothmann commented
![](https://github.trello.services/images/mini-trello-icon.png) [QDA Viz](https://trello.com/c/y9jBP6gK/191-qda-viz)

2022-05-30 16:13 UTC, laefrost commented on slides/supervised-classification/rsrc/fig-reg_class_qda.R
> +  means <- learner_qda$model$means
Ja, das stimmt absolut. Ich hatte das zuvor ohne function geschrieben und dann habe ich das wahrscheinlich übersehen als ich die function gemacht und die Übergabeparameter angepasst habe. 🤦‍♀️ Und weil ja alles noch im einvironment drinnen war, kam auch kein Fehler. Sorry dafür! Habs angepasst 👍

2022-06-01 12:48 UTC, ludwigbothmann approved these changes
Vielen Dank @laefrost !

2022-06-01 12:48 UTC, merged